version: 0.4

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - mvn package
      - echo build
  post_build:
    commands:
      - echo post_build
artifacts:
  files:
    - target/spring-boot-todo-rest-api-h2-aws-codepipline-0.0.1-SNAPSHOT.jar
